use_frameworks!
platform :ios, '11.0'

target 'RxWifi_Example' do
  pod 'RxWifi', :path => '../'

  target 'RxWifi_Tests' do
  inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
    pod 'RxNimble'
  end
end

