use_frameworks!
platform :ios, '11.0'

target 'RxWifi_Example' do
  pod 'RxWifi', :path => '../'

  target 'RxWifi_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
